// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package service;

public final class Service_Stub
    extends java.rmi.server.RemoteStub
    implements service.ServiceInterface, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getMyDate_0;
    
    static {
	try {
	    $method_getMyDate_0 = service.ServiceInterface.class.getMethod("getMyDate", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Service_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getMyDate()
    public service.MyDate getMyDate()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getMyDate_0, null, -7856715083053104458L);
	    return ((service.MyDate) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
